//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Windows;
using System.Windows.Media;
using System.Windows.Media.Effects;
using System.Windows.Media.Media3D;


namespace SberPank {
	
	public class GlassnoEffect : ShaderEffect {
		public static readonly DependencyProperty InputProperty = ShaderEffect.RegisterPixelShaderSamplerProperty("Input", typeof(GlassnoEffect), 0);
		public static readonly DependencyProperty TimeScaleProperty = DependencyProperty.Register("TimeScale", typeof(double), typeof(GlassnoEffect), new UIPropertyMetadata(((double)(1D)), PixelShaderConstantCallback(0)));
		public GlassnoEffect() {
			PixelShader pixelShader = new PixelShader();
			pixelShader.UriSource = new Uri("Effects/GlassnoEffect.ps", UriKind.Relative);
			this.PixelShader = pixelShader;

			this.UpdateShaderValue(InputProperty);
			this.UpdateShaderValue(TimeScaleProperty);
		}
		public Brush Input {
			get {
				return ((Brush)(this.GetValue(InputProperty)));
			}
			set {
				this.SetValue(InputProperty, value);
			}
		}
		/// <summary>Explain the purpose of this variable.</summary>
		public double TimeScale {
			get {
				return ((double)(this.GetValue(TimeScaleProperty)));
			}
			set {
				this.SetValue(TimeScaleProperty, value);
			}
		}
	}
}
